### PR TITLE
Feature/complex scopes

### PR DESCRIPTION
**Pull request by leio10**
#### :tophat: Scope of work
Changes proposal for complex scopes use on resources filters

#### :pushpin: Related Issues
- Related to decidim/decidim#1480 and decidim/decidim#1500

### :camera: URLs
imagen

### CODE REVIEW

**Comment by josepjaume** [comment]
Super nice @leio10 - @htmlboy or @martuishere will be able to give you a bit of feedback.

**Comment by oriolgual** [comment]
What happens when there's no scope selected? I'm worried that users won't know what to type since they don't know the existing scopes.

**Comment by leio10** [comment]
@oriolgual when there is no scope selected it would work as a selector with all the subscopes of the process scope (or top level scopes for global processes).

imagen

When you start typing then it would list subscopes of the process scope with names starting with that text.

imagen

**Comment by martuishere** [comment]
Maybe we could always force a line break for the text input (leaving the tags on top), to avoid having to start typing when there's only a few characters left?

Other than that, the solution looks good to me!

**Comment by xabier** [comment]
I am not sure this was sufficiently well discussed. I don't see the value of having the Scopes present at the navigation bar for a process. The very process should be classified unambiguously within a specific scope. It is categories and sub-categories that should be navigable and appear as filters, not scopes, these are fixed for a process, organ or initiative. Maybe I have missed something. 

We add a further, IMHO unnecessary complexity, by having scopes as variables inside instances of participatory spaces (initiatives, processes, organs). 

Anyway, if this is the situation now, and given that this PR is good, I see no obstacle on including it. But we urgently need to converge on the basic ontology of Decidim. We did a workshop on this during LAB.metadecidim las Friday: https://www.decidim.barcelona/processes/12/f/19/meetings/875?locale=es

**Comment by leio10** [comment]
@xabier I agree with you that scopes filter should not be a main navigation element. But I think that it could be useful for big scopes and specific resources, like events. So, maybe it could be hidden by default and only activated with a setting at a feature level. This settings would include the filter box and the scope tags that appears below each resource, because these are also a filtering tool.

**Comment by xabier** [comment]
In case it wasn't clear, OK with this PR. thanks for your comments @leio10

**Comment by josepjaume** [comment]
@leio10 @xabier that behavior is already present: When a Participatory Process is scoped via its settings, then no scope navigation appears on the sidebar. Otherwise it's considered a "city-wide" process and thus has scope navigation. Merging this and apologies for the delay!

**Pull request merged**
