### PR TITLE
Feature/consultations

### PR DESCRIPTION
**Pull request by htmlboy**
#### :tophat: Scope of work
HTML & CSS for the consultations feature interface.

### CODE REVIEW

**Comment by jsperezg** [comment]
@htmlboy I've downloaded this branch. I've set it up following the readme instructions but when I execute the app I can't find the link for consultations in the main menu. How can I access it in order to see it in action?

**Comment by htmlboy** [comment]
@jsperezg The links should be listed under the "Multiconsulta" block in the home index:

screen shot 2018-02-05 at 09 34 29

Can you find them?

**Comment by josepjaume** [comment]
Hi - this is unfortunate; we should actually be using `decidim_app-design` in the [decidim/decidim](https://github.com/decidim/decidim) repo. It shouldn't be that painful moving the changes there, the only difference it that's a rails application instead of a middleman one.

@htmlboy sorry for the misunderstanding!

**Comment by jsperezg** [comment]
I'll check againg @htmlboy 

Thanks

**Comment by htmlboy** [comment]
This PR is now on the right repo: https://github.com/decidim/decidim/pull/2667

**Pull request closed without merging**
