### PR TITLE
Project sync

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
#### :tophat: Scope of work
This PR syncronizes this project with what's in decidim/decidim#2185. That way we can land that PR without having to make a decision on whether to deprecate this project right now.

#### :pushpin: Related Issues
- Related to decidim/decidim#2185.

#### :clipboard: Subtasks
_None_.

### :camera: URLs
_None_.

#### :ghost: GIF (optional)
victory

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Seeing a lot of activity here, at least in terms of issue tracking. This PR should give any further work a base starting point where the stylesheets are fully synced with what's in decidim right now.

**Comment by mrcasals** [comment]
@deivid-rodriguez should we merge this?

**Comment by deivid-rodriguez** [comment]
I'd merge it, together with decidim/decidim#2185, yeah.

**Comment by josepjaume** [comment]
Closing this due to https://github.com/decidim/decidim/issues/2365 being accepted and merged.

**Pull request closed without merging**
